# -*- coding: utf-8 -*-
"""Iris_Flower_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dk2UccYxwRTIGOQmKpluhGU11aoMu9rM

# Iris Flower Classification

Aims to classify Iris flowers into three species (Setosa, Versicolor, and Virginica) using various machine learning algorithms.

By comparing the performance of **K-Nearest Neighbors (KNN), Logistic Regression, Decision Trees**, and **ensemble methods like Bagging and Boosting**, the aim is to identify the most effective approach for this classification task.
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

import warnings
warnings.filterwarnings("ignore")

# Load the Iris dataset
# Dataset contains measurements of for three species of Iris flowers.
# Use this dataset to train and test our KNN classifier.

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# X contains the features (sepal length, sepal width, petal length, petal width)
# y contains the target variable (class)
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pd.read_csv(url, names=names)

# Split the dataset into features and target variable
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Split the dataset into training and testing sets
# With 80% training data and 20% testing data.
# The model will be trained on the training data and evaluated on the testing data.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

# Ceate a KNN classifier with k=3
# The algorithm will consider the 3 nearest neighbors to make a prediction.
knn = KNeighborsClassifier(n_neighbors=3)

# Train the model
knn.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = knn.predict(X_test)

# Evaluate the model
# A higher accuracy score indicates a better performing model.
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print(classification_report(y_test, y_pred))

from sklearn.linear_model import LogisticRegression

# Create a Logistic Regression model
logreg = LogisticRegression(max_iter=1000)

# Train the model
logreg.fit(X_train, y_train)

# Make predictions
y_pred_logreg = logreg.predict(X_test)

# Evaluate the model
accuracy_logreg = accuracy_score(y_test, y_pred_logreg)
print("Accuracy of Logistic Regression:", accuracy_logreg)

from sklearn.tree import DecisionTreeClassifier

# Create a Decision Tree Classifier
dtree = DecisionTreeClassifier()

# Train the model
dtree.fit(X_train, y_train)

# Make predictions
y_pred_dtree = dtree.predict(X_test)

# Evaluate the model
accuracy_dtree = accuracy_score(y_test, y_pred_dtree)
print("Accuracy of Decision Tree:", accuracy_dtree)

"""Confusion Matrix"""

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

print(classification_report(y_test, y_pred))

"""# Combining KNN Models with Ensemble Methods
1. Bagging (Bootstrap Aggregating):

2. Boosting (AdaBoost):


"""

from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier

# Create a KNN classifier

knn = KNeighborsClassifier(n_neighbors=3)

# Create a Bagging classifier with 10 base estimators
bagging_clf = BaggingClassifier(estimator=knn, n_estimators=10, random_state=42)

# Train the Bagging classifier
bagging_clf.fit(X_train, y_train)

# Make predictions
y_pred = bagging_clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

# Create a KNN classifier
knn = KNeighborsClassifier()


# Create a Bagging classifier
bagging_clf = BaggingClassifier(estimator=knn, random_state=42)

# Define the hyperparameter grid
param_grid = {
    'n_estimators': [10, 50, 100],
    'max_samples': [0.5, 0.75, 1.0],
    'max_features': [0.5, 0.75, 1.0]
}

# Perform grid search with cross-validation
grid_search = GridSearchCV(bagging_clf, param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Get the best model
best_bagging_clf = grid_search.best_estimator_


# Train the Bagging classifier
best_bagging_clf.fit(X_train, y_train)

# Make predictions
y_pred = best_bagging_clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.ensemble import AdaBoostClassifier

# Create an AdaBoost classifier with 50 estimators
adaboost_clf = AdaBoostClassifier(n_estimators=50, random_state=42)

# Train the AdaBoost classifier
adaboost_clf.fit(X_train, y_train)

# Make predictions
y_pred = adaboost_clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# Create a Decision Tree classifier as the base estimator
dt = DecisionTreeClassifier()

# Create an AdaBoost classifier
adaboost_clf = AdaBoostClassifier(n_estimators=50, random_state=42)

# Define the hyperparameter grid
param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.1, 0.5, 1.0]
}

# Perform grid search with cross-validation
grid_search = GridSearchCV(adaboost_clf, param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Get the best model
best_adaboost_clf = grid_search.best_estimator_

# Train the AdaBoost classifier
best_adaboost_clf.fit(X_train, y_train)

# Make predictions
y_pred = best_adaboost_clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

cm = confusion_matrix(y_test, y_pred)
print(cm)